name: PR
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.9.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      - name: Scala formatting check
        run: ./tools/scalafmt --quiet --test
      - name: Build
        run: bazel build //...
      - name: Unit tests
        run: bazel test --test_tag_filters=unit //...
      - name: Integrations tests
        run: bazel test --test_tag_filters=integration //...